language: python
sudo: required
services:
- docker
env:
  global:
  - DOCKER_EMAIL=docker@hydrachain.com
  - DOCKER_USERNAME=hydrachain
  - secure: Rr+meswIU5zxFWscvMTfumD8Fj23lAaWIQuf2REo9NefTpOUvS3CFaZY/sTFZmUybV/IGSvRXZsQoYxYlrNCsTFqwQh5RXft+A9XjrzK8EPQPxugVROoRaKNrgrCKvfy/4mup2bvCz6xp0EmFILZteMTMoveI8FOJYdEmypHpwc9/HrgB6iGFcH8EB1Ny1kXKjHmubF3jnNtsTmxciFc2+ZuC4yVa7aAZU6DMWK72/tWN6qlR5sTY11nkcuWBI/ot4niAuSkWp4RYhXHPoVeewj+0gWNBWejzID6NWK6+tLUu917+xrmjKt30Whjva3+jsNiKVdBsNuDC9M7AXViBedmfzFaRUThotM9dgqVovG6RKW3Ybdqk4cQZldK3DYOF7uVuZ9CujOlf9zYIuGv6sUihd2j6jxLEgDqpC9yumZUBqAHUqegOUizybINNhpIhcQU83ynceaUARXsPdc6JFZziY9RsjNOFkRwRKo+O7o2OfvnA9XSkIWPF8hnt4hrXHdzuzLKqgbR6spiUczuEhosjf2tNk6KlSFk0+K1vx/lx0jd9GoCKdsO/MGnAmh5M0g2OFW1vaj1/td5tQh06qFiIFULlDfSSdDtH0rNUMTRVbiGDF6NzuECYHZ23s2zIMZAOpVWHlItWlG1faBbkKz9UV0P3lqv2bp5CAuAXqk=
  matrix:
  - TOXENV=py27
  - TOXENV=pypy
addons:
  apt:
    packages:
    - libgmp3-dev
install:
- pip install tox
- pip install coveralls
script: tox -- --ignore hydrachain/tests/test_sim_failures.py --ignore hydrachain/tests/test_sim_syncing.py
after_success:
- coveralls
- '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME"
  -p="$DOCKER_PASSWORD" || true'
- '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && docker build -t hydrachain/hydrachain:${TRAVIS_TAG:-develop}
  . || true'
- '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && docker push hydrachain/hydrachain:${TRAVIS_TAG:-develop}
  || true'
deploy:
  provider: pypi
  user: ethereum_pypi_automated
  password:
    secure: vO6kAkkpdqQz2+Le7aowcIkYHyvQzuNaL35c8ciHzmT2VdeGeCsDBGyJ8RYqITQruwfVzUsKsNjfCXBTcYan3e1vPpG9KKrkxB/Zy6KcNJmd+SL9n2tB6TVFr1ojxnRJgIzFBxbA1FnyY0aodwnMW2bJBlKxFIKJiKVjK6GGDl11wrMsudFFnvs3LkrPO9tr1plmN1xvVTNLzy0UmHjx6lmtjtZ/HMbx635WnFj5NnzdeMK07XD59HEuOYVvQ7BQua2cuCevFbXmSAxHJsDPZuhzYHkEfj+jPhKbS1MyTqD5W72ex2oPRmPlvvnOn01750IkSFSyO0lnZIv1wJuZ3+Y+49Q5XrFBAsuC4bqk1uOVL5hU37b2oDBIunJLQYEP1tn7TibVbv51iOolzx193tRR7KcbyU+pIqdP4a6rWDXT+PRada2JemX/Bx4G5hn9dXc4SmLP0+t7lcYpe/fTLQCGYsLNBbJv7iJdTuOeySX8Dlq9GYBMGreilDwIp5T4eqT4mhc25ZaXRel2HdqQSzie8SM88Sempn1V3uQkvQSUZ/PcwDwrG8wLK37BubaW0qVAZ5Zfkv1Q+pnVd7OkTEU+GgdOST6H3WGKVSO0fs/vLFYhQN0273IqM3Uuh3+s5h/sbGWfXqPMS8lu6febpglBCAxvkgKjwQ0in2S3Fo8=
  on:
    tags: true
    repo: HydraChain/hydrachain
    branch: develop
  distributions: sdist bdist_wheel
after_deploy:
- docker tag hydrachain/hydrachain:$TRAVIS_TAG hydrachain/hydrachain:latest
- docker push hydrachain/hydrachain:latest
notifications:
  slack:
    secure: qJyYhNa9Ld427maaO5s2aVtiKYpQfzow0oGP56LGoJVkxOlLXbLzvPtGh/EuCSUsSYAcdMyo64LyNfjjt6UdgCroMnmGYF9i5d2CkJait61TqrL8wB6B8FFNUDfd1bpilArKuY19D6TmHYj1xRqxIq37zePS4GyAq2EanBRTtSiA4++66sUEw+8u79VEFfxDT82k0qZTNys1Ph9X/Ss6MSE7UljTkytzwhcNLWlR0z68O4jgFfhdwB9pJTFL1/80JMUlpvJpE5QhMIMgYEKhQDEAA9u+m8npmVothZVrQFJwcVMTvV3Rh8JPcfQ8IqMkzpo3zkXfL2zMX2cUkGpoFxsmF+jWtaZX+NooRC+ptcvnZJXz3mRpwK3VfwL7trPl0Y0xGVy8CtfxsdLDBYv8YMItBCiX+CrdHLIbQw1WFDODNGmRhrGZEjAy2ti5RiR4+98QdMmezf2rhHta5ttN9Ig1kRnrAsDT2/AyU4sWfLZdYFbrXwR41yP9yi9Q4R+jKk31Okr/mkFLNLRuz3UtDOlfwjVFw+D8tI0zioOybv9TYkk7TCg9Ply6sIZPG9T7x8iAos+B4iufqGoFiUfeJW1oeRb5pIeytMc27LSG1Jedlznu98ct0TjjMZwSdzx9tMXX4eXu6kVP7vkR+5G2O6HL9AqhEjA9Lm4W+pqX0LI=
  webhooks:
    - secure: "koqn6tf8V20CzyFC1VokqiIrWihkDJ4LvChtZ0ZpmSdrOUUW/ZoXr0lANcpvKjztPhy2EDexHNOh6JFtUP6pbbmMCjUsFwYIFSfXbpElN2BUrxIVeUZ4rNB6fGNMZMY5lJqOHi38Ht2e4BlAsghkZIs8HzP9xVyrJi9npbOmIg1ns2JfqCLisT3zBEqQzOc+6vKkucbQr7eYMljN1ROv+V846NLHKIR86Egfo+4DVvbk06F6P4TBot8BgX0JzldIEpOCE6xFSX1ec1UHwP9c/Jm2thLgSUWPi1Uf28GObaETzgRwEQYlD9RgakAe4hvRj9F3nG4MCGRVnDEo2Axe0+4aJ6qOSH4HPkfkiLMQsud/I137kkDtuLDOBGEpn74Jry3wEKsMS6CcIf9PuXqFlvzCm8biY7kV2tzcmAZFBvp6fBnpN+C0697qRZbZw53GdvuXfO9d2Vllzhx7G42d/byLXuLRmapv09Ud2Ksj1GXjDOE8jp10B7dk3+kL0X8Jy0KhIQbq2+pGLUmtYGpm9B3rU6+PlxZKixE59I0xOr7TCkAr0gfv4lXwWxVfQFFRR4qWxgt88bBHsFCRFpvi4PP6oShww50DQ2bekZCIMY3g8fiBQExRChr9fGGylP1nGadc4muL0W9DeoZP/kBVf72+zzkkPyMW2mktT6APrrg="
